# Generated by Django 5.0 on 2023-12-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grades', models.CharField(max_length=1)),
            ],
        ),
    ]
