# Generated by Django 5.0 on 2023-12-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='grades',
            new_name='grade',
        ),
    ]
